# Generated by Django 3.2.2 on 2021-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifield1', models.IntegerField(verbose_name='Integer field 1')),
                ('ifield2', models.IntegerField(verbose_name='Integer field 2')),
                ('ifield3', models.IntegerField(blank=True, null=True, verbose_name='Integer field 3')),
                ('bfield4', models.BooleanField(verbose_name='Boolean field 4')),
                ('bfield5', models.BooleanField(blank=True, null=True, verbose_name='Boolean field 5')),
                ('tfield6', models.TextField(verbose_name='Text field 6')),
                ('tfield7', models.TextField(blank=True, null=True, verbose_name='Text field 7')),
            ],
        ),
    ]
