# Generated by Django 3.2.2 on 2021-05-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_perf_tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel1',
            name='index_field',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Index Field'),
        ),
    ]
