# Generated by Django 3.2.2 on 2021-05-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_perf_tester', '0003_alter_testmodel1_index_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel1',
            name='ifield2',
            field=models.IntegerField(db_index=True, verbose_name='Integer field 2'),
        ),
        migrations.AlterField(
            model_name='testmodel1',
            name='index_field',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Index Field'),
        ),
    ]
