# Generated by Django 3.2.2 on 2021-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_perf_tester', '0004_auto_20210512_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel1',
            name='index_field',
            field=models.IntegerField(default=0, verbose_name='Index Field'),
        ),
    ]
