# Generated by Django 3.2.2 on 2021-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_perf_tester', '0005_alter_testmodel1_index_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.IntegerField(verbose_name='PK From Other Model')),
                ('ifield2', models.IntegerField(verbose_name='Integer field 2 clone')),
            ],
        ),
        migrations.AlterField(
            model_name='testmodel1',
            name='ifield2',
            field=models.IntegerField(verbose_name='Integer field 2'),
        ),
    ]
