# Generated by Django 3.2.2 on 2021-05-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_perf_tester', '0006_auto_20210512_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='index_field',
            field=models.IntegerField(default=0, verbose_name='Index Field'),
        ),
    ]
